apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-rental
  template:
    metadata:
      labels:
        app: car-rental
    spec:
      containers:
      - name: car-rental
        # 
        # LIGNE IMPORTANTE : C'est le nom exact de votre image sur Docker Hub.
        # La pipeline Jenkins s'assurera que cette ligne est bien présente
        # avec le tag ':latest' grâce à la commande "sed".
        # 
        image: iheb99/luxury-car-rental:latest
        ports:
        - containerPort: 80
        env:
        # Ces variables connectent votre application au service MySQL
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "iheb" # Le même que dans mysql.yaml
        - name: DB_NAME
          value: "location_voiture_db"
