apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-rental-deployment # Nom mis à jour pour plus de clarté
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-rental
  template:
    metadata:
      labels:
        app: car-rental
    spec:
      containers:
      - name: car-rental
        image: iheb137/luxury-car-rental:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "iheb" # Utilisez le même que dans mysql.yaml
        - name: DB_NAME
          value: "location_voiture_db"