apiVersion: v1
kind: Service
metadata:
  name: car-rental
spec:
  selector:
    app: car-rental
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # Port accessible depuis l'extérieur
  type: NodePort
