apiVersion: v1
kind: Service
metadata:
  name: car-rental
spec:
  selector:
    app: car-rental
  ports:
    - protocol: TCP
      port: 80          # le port interne du conteneur Apache
      targetPort: 80    # idem
      nodePort: 30080   # le port accessible depuis ton hôte
  type: NodePort
